name: CI

on: 
  push: 
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch
        
      - name: Extract commit ish
        shell: bash
        run: echo "ish=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT
        id: extract_ish
        
      - name: Create the desired folder structure
        run: mkdir -p bin/x64/plugins/cyber_engine_tweaks/mods/NovaCityTools
        
      - name: Copy files to new folder structure
        run: |
          cp -r Debug bin/x64/plugins/cyber_engine_tweaks/mods/NovaCityTools/
          cp -r Modules bin/x64/plugins/cyber_engine_tweaks/mods/NovaCityTools/
          cp -r Resources bin/x64/plugins/cyber_engine_tweaks/mods/NovaCityTools/
          cp cloudCustomizer.lua bin/x64/plugins/cyber_engine_tweaks/mods/NovaCityTools/
          cp init.lua bin/x64/plugins/cyber_engine_tweaks/mods/NovaCityTools/
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nova-city-tools-${{ steps.extract_branch.outputs.branch }}-${{ steps.extract_ish.outputs.ish }}.${{ github.run_id }}
          path: bin/x64/plugins/cyber_engine_tweaks/mods/NovaCityTools/
